### ISSUE TITLE
Missing some files

### ISSUE THREAD

**Issue by MaximeThoonsen** [theodo/theodo-stack-generator#121] opened 2018-04-08 13:52 UTC
I just made a fresh install and it lacks:

- .gitignore
- registerServiceWorker.js
- index.html

**Comment by benja-M-1** [comment] 2018-04-08 18:28
What did yo uinstall? Only a react app?

**Comment by MaximeThoonsen** [comment] 2018-04-09 08:15
OK I'll do that

**Comment by MaximeThoonsen** [comment] 2018-04-09 10:25
![image](https://user-images.githubusercontent.com/4814551/38493008-fd64b43c-3bf0-11e8-8069-bcb6af23261a.png)

done @benja-M-1 
I've git cloned the repo + npm link it

**Comment by tcheymol** [comment] 2018-07-31 10:02
@MaximeThoonsen

* I think we are not experienced enough in PWA to provide a good SW
* For the 2 other files, I got them, can you try again ? (you can `npm unlink` and then reinstall it since it has been released on npm)

**Comment by benja-M-1** [comment] 2018-08-28 14:46
Nobody can reproduce this so I close this issue. I hope @MaximeThoonsen won't get the issue again.

**Closed by benja-M-1** 2018-08-28 14:46 UTC
Labels: Priority #1, bug
